version: '3'

services:
    web:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - ./web/conf.d:/etc/nginx/conf.d
            - reverse-proxy_nginx-static:/usr/share/nginx/html
        environment:
            VIRTUAL_HOST: localhost
            LETSENCRYPT_HOST: localhost
            LETSENCRYPT_EMAIL: xxx@gmail.com
            LETSENCRYPT_TEST: "true"  # comment out in production
            HTTPS_METHOD: noredirect  # comment out in production
            CERT_NAME: default        # comment out in production
        depends_on:
            - app
        networks:
            - frontend
            - reverse-proxy_proxy
    app:
        build: ./app
        image: min_app
        container_name: app
        depends_on:
            - db
        networks:
            - frontend
            - backend
    db:
        image: mariadb
        container_name: mariadb
        volumes:
            - ./db/init.d:/docker-entrypoint-initdb.d
            - db_volume:/var/lib/mysql
        environment:
            - MARIADB_ROOT_PASSWORD
        networks:
            - backend

volumes:
    db_volume:
    reverse-proxy_nginx-static:
        external: true

networks:
    frontend:
    backend:
    reverse-proxy_proxy:
        external: true