version: '3'

services:
    web:
        image: nginx
        container_name: nginx
        ports:
            - 8080:8080
        volumes:
            - ./web/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - frontend
    app:
        build: ./app
        image: min_app
        container_name: app
        depends_on:
            - db
        networks:
            - frontend
            - backend
    db:
        image: mariadb
        container_name: mariadb
        volumes:
            - ./db/init.d:/docker-entrypoint-initdb.d
            - db_volume:/var/lib/mysql
        environment:
            - MARIADB_ROOT_PASSWORD
        networks:
            - backend

volumes:
    db_volume:

networks:
    frontend:
    backend: